### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by sjohnsonaz**
I changed the code to use TypeScript.  Originally I was just creating the type definition files, but then realized it would be easier to convert the project.  The code should run identically, and I kept the dependencies the same.

I also added API types for the data interacting with the server.  They work really well for Upload, Asset, etc.  There are a couple missing, specifically LiveStream and SimulcastTarget.

I also fixed the linting, although there are some minor linting issues still.

Let me know if you have any questions.  I hope this helps you guys!

### CODE REVIEW

**Comment by sjohnsonaz** [comment]
It looks like the builds aren't working with the compiled files.  I can try and update some of the configs.

**Comment by dylanjha** [comment]
@sjohnsonaz I appreciate all the effort you put in here. I'm afraid the way the team is leaning right now is that we don't want to rewrite this whole library in TypeScript. I'll explain our reasoning.

Firstly, again I want to say that we appreciate all the work you put into this - it's certainly a lot and I thank you for taking an interest in helping out.

We like TypeScript and we use it internally in our dashboard react application, but for this library we kind of like keeping it as javascript for a few reasons. First of all, there's no way I could reasonably review this PR and do enough QA to make sure there are no regressions. That alone is a tall task and we have many developers using this library already and we need to be careful to not break anyone's application.

Part of the reason we like using javascript instead of TypeScript for this project is to keep the library easily accessible for anyone using it and wanting to dive in to debug or contribute. Raising the barrier to entry by requiring TypeScript knowledge and adding extra build steps makes it much less accessible to developers that do not work with TypeScript.

We're FULLY onboard for having defined types to support TypeScript users, but it seems a bit unfeasible to rewrite the whole library and make all these changes, change the build process and add new dependencies all while ensuring we don't have regressions. Sure there are pros and cons, but the pros don't really feel like they outweigh the cons of a big change like this. If the pros were really heavy it could out-weigh the cons and the risks associated with this change but in this instance it doesn't feel like we're getting enough benefit out of it.

Again, I want to re-iterate two things. First, I really appreciate the interesting you have in helping out and the work you put in. I feel bad that you put all this work in that we're not going to use. And second, we fully intend to have defined types for this library.

I hope our reasoning makes sense, thanks again for your PR and this still definitely qualifies you for the [contributor program](https://mux.com/oss/#contributor-program) so I'm happy to throw some extra Mux credit your way and send you some swag if you would like.

**Comment by smolster** [comment]
@dylanjha Question: Are there any plans for the internal Mux team to provide type declaration (`.d.ts`) files for the library?

**Comment by dylanjha** [comment]
@smolster this is in-progress as we speak! Stay tuned the next couple weeks

**Comment by dylanjha** [comment]
closing in favor of #51. @sjohnsonaz thanks for pushing us forward on this!

**Comment by dylanjha** [comment]
Update on typescript support- it's on the `v3.0.0-beta.1` tag. More info here:

https://github.com/muxinc/mux-node-sdk/issues/44#issuecomment-646727258

**Comment by sjohnsonaz** [comment]
@dylanjha I'm glad I was able to help get things rolling on this!  Super excited to use your library with TypeScript!

**Pull request closed without merging**
