### PR TITLE
Update dependencies to address security issues

### PR DESCRIPTION
**Pull request by jaredsmith**
Signed-off-by: Jared Smith <jsmith@mux.com>

### CODE REVIEW

**Comment by aliwatters** [comment]
Thanks for digging in -- running `npm audit` on this branch still has critical issues for me;

```
mux-node-sdk on  fix-security-issues [$!?] is 📦 v7.0.0 via  v16.16.0 via 💎 v3.0.0
❯ npm audit fix
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 2 packages, removed 14 packages, changed 22 packages, and audited 495 packages in 2s

80 packages are looking for funding
  run `npm fund` for details

# npm audit report

jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98
No fix available
node_modules/jsdom
  cheerio  0.19.0 - 1.0.0-rc.3
  Depends on vulnerable versions of css-select
  Depends on vulnerable versions of jsdom
  node_modules/cheerio
  node_modules/esdoc-brand-plugin/node_modules/cheerio
  node_modules/esdoc-publish-html-plugin/node_modules/cheerio
  node_modules/ice-cap/node_modules/cheerio
    esdoc-brand-plugin  *
    Depends on vulnerable versions of cheerio
    node_modules/esdoc-brand-plugin
      esdoc-standard-plugin  *
      Depends on vulnerable versions of esdoc-brand-plugin
      node_modules/esdoc-standard-plugin
    ice-cap  >=0.0.4
    Depends on vulnerable versions of cheerio
    node_modules/ice-cap
      esdoc  >=0.1.0
      Depends on vulnerable versions of cheerio
      Depends on vulnerable versions of ice-cap
      Depends on vulnerable versions of marked
      Depends on vulnerable versions of minimist
      node_modules/esdoc
      esdoc-publish-html-plugin  *
      Depends on vulnerable versions of cheerio
      Depends on vulnerable versions of ice-cap
      Depends on vulnerable versions of marked
      node_modules/esdoc-publish-html-plugin

marked  <=4.0.9
Severity: high
Inefficient Regular Expression Complexity in marked - https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
Inefficient Regular Expression Complexity in marked - https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
Marked ReDoS due to email addresses being evaluated in quadratic time - https://github.com/advisories/GHSA-xf5p-87ch-gxw2
fix available via `npm audit fix`
node_modules/marked

minimist  <=1.2.5
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
No fix available
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select

11 vulnerabilities (2 moderate, 7 high, 2 critical)

```

are you able to dig in on those?

**Comment by aliwatters** [comment]
Also -- if you're able on this repo -- dependabot is really nice as a backstop for this type of thing. https://github.com/muxinc/mux-node-sdk/settings

`yarn audit` passes though -- I'm not sure on it's effectiveness vs npm.

**Comment by aliwatters** [comment]
FYI: `"@mux/mux-node": "github:@muxinc/mux-node-sdk#fix-security-issues",` pulled in to our npm managed repo has same issues flagged.

**Comment by jaredsmith** [comment]
> `yarn audit` passes though -- I'm not sure on it's effectiveness vs npm.

This is because I added a `resolutions` section to package.json, which yarn respects but NPM doesn't.

**Comment by jaredsmith** [comment]
> Also -- if you're able on this repo -- dependabot is really nice as a backstop for this type of thing. https://github.com/muxinc/mux-node-sdk/settings

Yes, we've had mixed results with dependabot in the past, but it seems to have improved over the past six months, so I'll work to get it turned back on for this repo.

**Review by aliwatters — CHANGES_REQUESTED** [review]
Add to package.json to support npm.

```
"overrides": {
    "jsdom": "^16.5.0",
    "marked": "^4.2.12",
    "minimist": "^1.2.7",
    "nth-check": "^2.0.1"
  },
```

**Comment by jaredsmith** [comment]
Abandoning this PR in lieu of PRs from dependabot (See #206, #207, #208, #209, #210.)

**Comment by aliwatters** [comment]
please also bump the version in package.json :)

**Review by aliwatters — APPROVED** [review]

**Comment by jaredsmith** [comment]
> please also bump the version in package.json :)

The version has already been bumped in the `master` branch, but I'll merge this before cutting the `7.1.0` release.

**Pull request merged**
