### PR TITLE
Add missing parameter

### PR DESCRIPTION
**Pull request by Danue1**
ref. https://github.com/muxinc/mux-node-sdk/blob/4659f3409d04ecac0555d9dcf22ac49c4e77f569/src/video/resources/assets.js#L133-L158

### CODE REVIEW

**Review by dylanjha — APPROVED** [review]
LGTM!

**Comment by Danue1** [comment]
Thanks!
When can we merge this?

**Comment by Danue1** [comment]
Wow, cool!

**Comment by dylanjha** [comment]
Released in 3.1.4, thanks! https://www.npmjs.com/package/@mux/mux-node

**Pull request merged**
