### PR TITLE
Add 'real-time' support to JWT signing

### PR DESCRIPTION
**Pull request by refactornator**

### CODE REVIEW

**Review by philcluff — CHANGES_REQUESTED** [review]
https://github.com/muxinc/mux-node-sdk/pull/194/files#diff-bc3253061283423c721c833f262624f2ba8b6073381c5122cc6671b500cfc743R93

Unfortunately I think this needs more head scratching before we merge it. 

While it'll work, the interface here becomes weird, because we tell people to call `sign` with a Playback ID, which is distinct from a Space ID. 

Some options:

1) Change the SDK so that the first param is specifically called out as the `subject`, rather than the Playback ID
2) Add a second interface to `sign` ?

Something else? Would love some guidance from @muxinc/techops here.

**Comment by refactornator** [comment]
I'm happy to make any changes here to get this merged, but I need some guidance from @muxinc/techops since the API will change.

**Comment by andrewjl-mux** [comment]
I'm leaning toward a combination of options 1 & 2 that @philcluff suggested.

I noodled a bit on a way to preserve the existing SDK API and avoid breaking changes when adding a second interface. What about adding the following sign method that takes a `subject` and also a `type`?

```
static sign(subject: string, type: string, options: MuxJWTSignOptions = {}) {
    const opts = {
      type: type,
      expiration: '7d',
      params: {},
      ...options,
    };

    const keyId = getSigningKey(options);
    const keySecret = getPrivateKey(options);

    // TODO: come back through sometime and replace this with runtypes validation?
    // @ts-ignore
    const typeClaim = TypeClaim[opts.type];
    if (!typeClaim) {
      throw new Error(`Invalid signature type: ${opts.type}`);
    }

    const tokenOptions: jwt.SignOptions = {
      keyid: keyId,
      subject: subject,
      audience: typeClaim,
      expiresIn: opts.expiration,
      noTimestamp: true,
      algorithm: 'RS256',
    };

    return jwt.sign(opts.params, keySecret, tokenOptions);
  }
```

This gives us the option to leave `static sign(playbackId: string, options: MuxJWTSignOptions = {})` as is or to refactor it to use the above which is more generic. I am not super familiar with specifics of method overloading in TS however, does anyone see any issues with the above? What do y'all think of this in general? @refactornator @philcluff @muxinc/techops

**Comment by refactornator** [comment]
I think that's a solid idea for avoiding breaking the API. I got curious to see how to do this in TS and the code is relatively simple, but quite ugly. I had to do some very gross conditional logic, but tests pass and it does work. https://github.com/muxinc/mux-node-sdk/pull/194/files#diff-bc3253061283423c721c833f262624f2ba8b6073381c5122cc6671b500cfc743R123-R133

If this isn't the direction we should move in, I can always revert, but figured I would at least try it out.

**Comment by philcluff** [comment]
Hey @refactornator and @andrewjl-mux, thanks for the work on this, I chatted with @jaredsmith this morning who is going to own getting this across the line 👍🏻

**Comment by jaredsmith** [comment]
We decided to take the approach in https://github.com/muxinc/mux-node-sdk/pull/199 instead -- can we close this PR now?

**Pull request closed without merging**
